Add Community Group and Corresponding Contribute Overview
iearn-finance/yearn-docs pull request #111
Opened 2020-11-10 21:21 UTC by Faolain

**Additions:**
- Community Group for Contribution to live under which will in the future include more information regarding hackathons, yAcademy and others.
- Contributor's Page see: https://github.com/iearn-finance/docs/issues/85

2020-11-11 20:18 UTC, milkyklim requested changes
Need more polishing.

2020-11-11 20:18 UTC, milkyklim commented on community/README.md
> +## Yearn Community
There is no `community` rather `contributors`.

2020-11-11 20:18 UTC, milkyklim commented on community/README.md
> +Currently we use [Canny](https://yearnfinance.canny.io/) to raise general feedback.
Canny is dead.

2020-11-11 20:18 UTC, milkyklim commented on community/README.md
> +If you want a general overview of how our various services interact with one another for Vaults please see the schema and accompanying descriptions at **[Vaults Overview](https://docs.yearn.finance/d
`[yDAI]()` empty link.

2020-11-11 20:18 UTC, milkyklim commented on community/README.md
> +You can find us over on [Discord](https://discord.com/invite/6PNv2nF) at the #ui-ux channel and you can see our work log on our [Kanban Board](TODO: Create Design Project Board).
`TODO:` not done!

2020-11-11 20:18 UTC, milkyklim commented on community/README.md
> +  - [Blue Kirby](https://twitter.com/bluekirbyfi)
🍴

2020-11-12 02:45 UTC, Faolain commented on community/README.md
> +## Yearn Community
hmm so this was generated via gitbook under Community (which we had talked about on the call would be the place for contribution docs to live similar to Maker's Community Portal). Does this structure not make sense with this mind for gitbook?

2020-11-12 03:01 UTC, Faolain commented on community/README.md
> +Currently we use [Canny](https://yearnfinance.canny.io/) to raise general feedback.
Hmm I can remove but whenever I wrote the initial iteration it seemed to have been alive. I see there are still posts on there but can remove from this doc and replace with https://gov.yearn.finance/c/feedback/2

2020-11-12 03:08 UTC, Faolain commented on community/README.md
> +  - [Blue Kirby](https://twitter.com/bluekirbyfi)
this section shows its age haha been sitting around for a while, will remove (was the source of the original links)

2020-11-12 03:12 UTC, Faolain commented on community/README.md
> +You can find us over on [Discord](https://discord.com/invite/6PNv2nF) at the #ui-ux channel and you can see our work log on our [Kanban Board](TODO: Create Design Project Board).
Removing for now as I don't see demand for UI/UX board 🤷‍♂️

2020-11-12 03:17 UTC, Faolain commented on community/README.md
> +If you want a general overview of how our various services interact with one another for Vaults please see the schema and accompanying descriptions at **[Vaults Overview](https://docs.yearn.finance/d
Removed, only static image exists which can be confusing, will re-add with animation if/when finished or applicable.

2020-11-12 03:17 UTC, Faolain commented
Updated

2020-11-17 00:05 UTC, milkyklim approved these changes

2020-11-17 00:05 UTC, merged