Add Writing Style Guide
iearn-finance/yearn-docs pull request #132
Opened 2020-12-04 16:30 UTC by Faolain

2020-12-04 16:34 UTC, Faolain commented
Not sure why the linter failed, ran npm run lint:fix & npm run lint:check and everything seemed to be fine
![Screen Shot 2020-12-04 at 11 33 14 AM](https://user-images.githubusercontent.com/9613083/101189148-a763f300-3624-11eb-94a2-9e8128433c90.png)

2020-12-08 16:56 UTC, lehnberg requested changes
Good job, this is really great! See my nitpicky comments.

2020-12-08 16:56 UTC, lehnberg commented on SUMMARY.md
Consider also linking to this guide from `contributors/README.md`

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +- Provide examples to help explain concepts, but avoid overcomplicating them.
"overcomplicating" → "complicating" :)

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +- Check out the [Getting Started guide]() for contributing to Documentation.
Broken link, insert destination URL

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +This document could not be possible without the amazing work done by the MakerDAO team as this document is mostly based on their [Writing Style Guide](https://github.com/makerdao/community-portal/blo
Hyperlink is in violation of current style guide instructions (doesn't include the `.`).

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +---
delete `---` as it's redundant

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +**Use:**
Consider using the level 4 header `####` for these throughout the document instead of bold text.

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +- Ordered list items should use the `#1` repeated.
actually should use `1. ` repeated -- `#1` is not valid markdown afaik

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +  - **Descriptive:** Learn more at [Yearn Documentation](https://docs.yearn.finance/)
Rather than **Descriptive:** and **Generic:** , should this be **Correct:** and **Incorrect:** for consistency?

2020-12-08 16:56 UTC, lehnberg commented on contributors/writing-style-guide.md
> +- Include a `.`inside the link for sentences that end with a link.
Personally, this feels like unexpected behaviour, I never use or see this being used.

Also note that this document is in violation of this (at the very end, raised a comment).

If it was up to me, my vote would go to keeping the `.` _outside_ of the link. :)  

But, this is your call, as long as it's consistent. 👍

2020-12-10 01:48 UTC, Faolain commented on contributors/writing-style-guide.md
> +**Use:**
hmm may push back on this one here haha since a header implies/indicates some distinct "Class"/Section which everything lives under that merits its own heading (especially if we autogenerate ToC). In this case, the bold just serves to stress I think which should suffice?

2020-12-10 01:51 UTC, Faolain commented on contributors/writing-style-guide.md
> +- Ordered list items should use the `#1` repeated.
yep good catch!

2020-12-10 01:52 UTC, Faolain commented on SUMMARY.md
will submit to the main contributors README all the following links once done  (writing style guide, getting started with gitbook & github etc) hehe

2020-12-10 01:54 UTC, Faolain commented on contributors/writing-style-guide.md
> +  - **Descriptive:** Learn more at [Yearn Documentation](https://docs.yearn.finance/)
hmm this is taken from the wording which exists on the Maker docs and I think I agree with their usage of Generic and Descriptive explaining the difference between the two. Can maybe Add a modifier in parens which explains which one is correct to ensure it's clear?

2020-12-10 01:55 UTC, Faolain commented on contributors/writing-style-guide.md
> +- Include a `.`inside the link for sentences that end with a link.
agreed I think outside of the link too :)

2020-12-10 01:58 UTC, Faolain commented on contributors/writing-style-guide.md
> +- Check out the [Getting Started guide]() for contributing to Documentation.
ah hmm not merged yet (one of the prereqs to merge this one), ok to put the destination URL which will be merged in shortly after this one?

2020-12-10 02:00 UTC, Faolain commented on contributors/writing-style-guide.md
> +This document could not be possible without the amazing work done by the MakerDAO team as this document is mostly based on their [Writing Style Guide](https://github.com/makerdao/community-portal/blo
fixed :p

2020-12-10 17:16 UTC, lehnberg commented on SUMMARY.md
Yes, sure 👍

2020-12-10 17:18 UTC, lehnberg commented on contributors/writing-style-guide.md
> +**Use:**
Sure, fair enough. Good push back! 👍

2020-12-11 19:35 UTC, lehnberg approved these changes

2020-12-11 19:39 UTC, lehnberg requested changes
@Faolain the CI reports back broken links:

```
ERROR: 5 dead links found!
349
[✖] developers/naming-convention.md → Status: 400
350
[✖] [https://docs.microsoft.com/en-us/contribute/how-to-write-links](https://docs.microsoft.com/en-us/contribute/how-to-write-links) → Status: 400
351
[✖] /en/contribute/content/ → Status: 400
352
[✖] https://www.powerthesaurus.org/ → Status: 403
353
[✖] contributors/contributor-tools.md → Status: 400
354
```

→ Can you update with these fixed pls? Sorry, didn't catch this until I was about to merge it. :/

2020-12-11 21:44 UTC, Faolain commented
> @Faolain the CI reports back broken links:
> 
> ```
> ERROR: 5 dead links found!
> 349
> [✖] developers/naming-convention.md → Status: 400
> 350
> [✖] [https://docs.microsoft.com/en-us/contribute/how-to-write-links](https://docs.microsoft.com/en-us/contribute/how-to-write-links) → Status: 400
> 351
> [✖] /en/contribute/content/ → Status: 400
> 352
> [✖] https://www.powerthesaurus.org/ → Status: 403
> 353
> [✖] contributors/contributor-tools.md → Status: 400
> 354
> ```
> 
> → Can you update with these fixed pls? Sorry, didn't catch this until I was about to merge it. :/

No worries, hmm I'm not sure I know how to fix these? 

- For `developers/naming-convention.md → Status: 400` I currently reference it as `[Yearn Naming Conventions](developers/naming-convention.md)`. Should it instead be `[Yearn Naming Conventions](../developers/naming-convention.md)` to account for the folder structure? I'm not sure how one can reference another page using relative links, if it's relative to the current folder or if it uses the root of the gitbook project. I'm unable to build this locally to test so would love to know for future reference (maybe we can also include this information in the guide - very meta lol). 

- I was able to visit https://docs.microsoft.com/en-us/contribute/how-to-write-links so I'm not sure what this linter wants here?

- `/en/contribute/content/ ` I can just change to match the absolute link 

-  `https://www.powerthesaurus.org/` also seems to work not sure what it is failing?

-  Similar relative link question as #1 and dependency to be merged in here (which thanks for reminding me to submit hah) https://github.com/iearn-finance/yearn-docs/issues/101

2020-12-14 17:00 UTC, lehnberg approved these changes
Approving, and merging. CI failed, due to it marking https://www.powerthesaurus.org as broken, but it's not so going ahead.

2020-12-14 17:00 UTC, merged