trying to fix the image zoom on click issue
iearn-finance/yearn-docs pull request #175
Opened 2020-12-14 14:26 UTC by miguel567

Images on this page are not zoomable: https://docs.yearn.finance/how-to-guides/how-to-withdraw-from-yearn-and-yvaults

2020-12-14 17:07 UTC, lehnberg requested changes
See comment above on numbering, you also missed to apply the same treatment to the table at the very bottom of the page

2020-12-14 17:07 UTC, lehnberg commented on how-to-guides/how-to-withdraw-from-yEarn-and-yVaults.md
>  1. Enter the amount you wish to withdraw:
Doing this change is breaking the numbering of the bullets, see the a preview of the page here: 
https://github.com/iearn-finance/yearn-docs/blob/007688478654a1cae846914ced6abb40e0c88a36/how-to-guides/how-to-withdraw-from-yEarn-and-yVaults.md

Possible ways to fix this might be to remove step numbering altogether?

2020-12-14 17:37 UTC, miguel567 commented on how-to-guides/how-to-withdraw-from-yEarn-and-yVaults.md
>  1. Enter the amount you wish to withdraw:
fixed! thanks for checking, forgot about the table and numbering. Not sure if it will look good now in Gitbook, but both things are fixed: numbering and lower table.

2021-01-23 19:12 UTC, miguel567 commented
Adding also V2 pages with Vasa's graphs.
Updating some V1 pages and giving them a bit less relevance in the Menu structure.

2021-01-23 19:24 UTC, miguel567 commented
Solved the request from @lehnberg  on the table in the page which was not zoomable.

2021-01-24 17:54 UTC, miguel567 commented
The pages changes can be reviewed in my personal gitbook:

https://miguel567.gitbook.io/yearn/products/yvaults-1/v2-yvaults
https://miguel567.gitbook.io/yearn/products/yvaults-1/v2-yvaults/strategies-and-yvaults-availbale

https://miguel567.gitbook.io/yearn/products/yvaults-1
https://miguel567.gitbook.io/yearn/products/yvaults-1/yvaults

https://miguel567.gitbook.io/yearn/developers/yvaults-documentation
https://miguel567.gitbook.io/yearn/developers/yvaults-documentation/v2-yvaults

2021-01-30 21:29 UTC, miguel567 commented
closing this disaster xD

2021-01-30 21:29 UTC, closed without merging